name: Docker Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t a-healthy-dns:test .

    - name: Test Docker image builds successfully
      run: |
        # Verify the image was created
        docker images a-healthy-dns:test

    - name: Test Docker image with minimal configuration
      run: |
        # Start the DNS server in the background with minimal valid config
        docker run -d \
          --name a-healthy-dns-test \
          -p 53053:53053/udp \
          -e DNS_HOSTED_ZONE="test.example.com" \
          -e DNS_ZONE_RESOLUTIONS='{"www":{"ips":["127.0.0.1"],"health_port":80}}' \
          -e DNS_NAME_SERVERS='["ns1.test.example.com"]' \
          -e DNS_LOG_LEVEL="debug" \
          a-healthy-dns:test

    - name: Wait for DNS server to start
      run: |
        # Wait a bit for the server to fully start
        sleep 10
        
        # Check if container is still running
        docker ps | grep a-healthy-dns-test

    - name: Test DNS server functionality
      run: |
        # Install dig for testing
        sudo apt-get update && sudo apt-get install -y dnsutils
        
        # Test DNS query (should get a response, even if NXDOMAIN)
        # Using timeout to avoid hanging
        timeout 10s dig @127.0.0.1 -p 53053 www.test.example.com || echo "DNS query completed (expected behavior for test)"

    - name: Test docker-compose configuration
      run: |
        # Test that docker-compose example file is valid
        if [ -f docker-compose.example.yml ]; then
          # Install docker-compose
          sudo apt-get install -y docker-compose
          
          # Validate the compose file syntax
          docker-compose -f docker-compose.example.yml config > /dev/null && echo "✓ docker-compose.example.yml is valid"
        else
          echo "docker-compose.example.yml not found"
        fi

    - name: Cleanup
      if: always()
      run: |
        # Stop and remove test container
        docker stop a-healthy-dns-test || true
        docker rm a-healthy-dns-test || true
        
        # Remove test image
        docker rmi a-healthy-dns:test || true
